name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [opened, reopened]
    branches: [ "main" ]
  push:
    branches:
      - "*"
    tags:
      - "run-tests"
  
  repository_dispatch:
    types: [CI]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-test-one:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  call-test-two:
    uses: ./.github/workflows/test-two.yml
    secrets: inherit
